### ISSUE TITLE
futurizeP -> response.json() [clarification]

### ISSUE THREAD

**Issue by djleonskennedy** [stoeffel/futurize#64]
I had situation with resolve `fetch` promises that should return `json`

fetch(`<apiUrl>`)
    .then(response => response.json())
    .then(json => json)

so i decided to make this

```
const Task = require("data.task");

const fetchJsonTask = promise =>
  new Task((rej, res) =>
    promise
      .then(response => response.json(),
            error => rej(error))
      .then(res));

module.exports = {
  fetchJsonTask
};

```
for this code:
```
const Task = require("data.task");
const Either = require("data.either");
const fetch = require('node-fetch');
const {List, Map} = require('immutable-ext');
const {fetchJsonTask} = require('../utils');

const requiredUserIDs = List([1, 2, 10]);

const getUser = apiUrl => Id =>
  fetchJsonTask(fetch(`${apiUrl}/${Id}`));

const decodeUser = ({id, name, username, email }) => // user
  Map({ id, name, username, email})
    .map(item => Either.fromNullable(item)
    .fold(e => 'Not Specified', r => r));

requiredUserIDs.traverse(Task.of, getUser('https://jsonplaceholder.typicode.com/users'))
  .map(list => list.map(decodeUser))
  .fork(console.error, console.log);
```
but this avoids to use your library, 

Have i done something wrong or could you extend your library ?

Thank you

**Comment by Avaq** [comment]
Hello @djleonskennedy,

I would say you've done something wrong. Most prominently the fact that you are converting a Promise to a Task directly, which defeats the benefit of laziness you get from using a Task. You see, the Promise is already executing as soon as you instantiate it. Passing it to a function that wraps it in a Task doesn't prevent the Promise from executing and causing its side-effects.

For this reason, in order to stay lazy, `futurizeP` doesn't take a Promise directly, but rather the function which generates the Promise.

Normally you would use this as such:

```js
const fetch_ = require('node-fetch');
const fetch = futurizeP(fetch_);
fetch('...').map(result => result);
```

However, I can see the inconvenience of then having to do `futurizeP(result.json.bind(result))()` for parsing the response as JSON. I would probably do it like this:

```js
const Task = require('data.task');
const fetch = require('node-fetch');

//    futurizeP :: (* -> Promise a b) -> * -> Task a b
const futurizeP = require('futurize').futurizeP(Task);

//    fetchJson_ :: Url -> Promise Error Object
const fetchJson_ = url => fetch(url).then(res => res.json());

//    fetchJson :: Url -> Task Error Object
const fetchJson = futurizeP(fetchJson_);

//    getUser :: Url -> UserId -> Task Error Object
const getUser = apiUrl => Id => fetchJson(`${apiUrl}/${Id}`);
```

**Comment by djleonskennedy** [comment]
@Avaq Now its clear, Thank you for help
